# Generated by Django 5.1 on 2024-09-02 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_task_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='title',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='important',
            new_name='relevante',
        ),
    ]
