# Generated by Django 5.1 on 2024-09-02 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_imagen_contact_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='imagen',
        ),
    ]
